package util;

import java.util.ArrayList;

/**
 * <p>The Class PeakInfo.
 * <p>This class represents a peak. It contains all possible fragments with m/z
 * of this peak. These fragments are fragmentated from one specific candidate
 * structure .
 * 
 */
public class PeakInfo {

    /** 
     * The M/Z of this peak. 
     * In ScoreModel.theroExpSpMatch, this m/z is m/z of real peaks.
     */
    double peakMz;
    
    /** The intensity of this peak
     * (seemingly the relative intensity with the highest one 100). 
     */
    double peakIntens;
    
    
    /** The relative intensity of this peak. */
    double peakRelativeInts;
    
    /** The absolute intensity of this peak. */
    double peakAbsoluteInts;
    
    /** 
     * The list containing all possible fragments that generated by a specific
     * candidate structure.??
     */
    ArrayList<FragNode> candiFragNodeList;
    
    /** 
     * The sum intensity of all peaks in **experimental(real)** spectrum. 
     * This is used in 
     * ScoreModel.theroExpSpMatch(ArrayList<FragNode>, Peak[], double).
     */
    double sumIntens;

    public PeakInfo(double peakMz, double peakIntens, ArrayList<FragNode> candiFragNodeList) {
        this.peakMz = peakMz;
        this.peakIntens = peakIntens;
        this.candiFragNodeList = candiFragNodeList;
    }

    public PeakInfo(double peakMz, ArrayList<FragNode> candiFragNodeList) {
        this.peakMz = peakMz;
        this.candiFragNodeList = candiFragNodeList;
    }

    public void setSumIntens(double sumIntens) {
        this.sumIntens = sumIntens;
    }

    public double getPeakMz() {
        return this.peakMz;
    }

    public void setPeakMz(double peakMz) {
        this.peakMz = peakMz;
    }

    public void setPeakIntens(double peakIntens) {
        this.peakIntens = peakIntens;
    }
    
    public void setPeakRelativeIntens(double ints){
        this.peakRelativeInts = ints;
    }
    
    public void setPeakAbsoluteIntens(double ints){
        this.peakAbsoluteInts = ints;
    }

    public double getPeakIntens() {
        return this.peakIntens;
    }
    
    public double getRelativeIntens(){
        return this.peakRelativeInts;
    }
    
    public double getAbsoluteIntens(){
        return this.peakAbsoluteInts;
    }
    
    public ArrayList<FragNode> getCandiFragNodeList() {
        return this.candiFragNodeList;
    }

    public double getSumIntens() {
        return this.sumIntens;
    }
    
}
