package util;

import java.util.ArrayList;

/**
 * <p>The Class PeakInfo.
 * <p>This class represents a peak. It contains all possible fragments with m/z
 * of this peak. These fragments are fragmentated from one specific candidate
 * structure .
 * 
 */
public class PeakInfo {

    /** The M/Z of this peak. */
    double peakMz;
    
    /** The intensity of this peak.(whether this intensity is relative?) ?? */
    double peakIntens;
    
    /** 
     * The list containing all possible fragments that generated by a specific
     * candidate structure.??
     */
    ArrayList<FragNode> candiFragNodeList;
    
    /** 
     * The sum intens. ?? what does this mean? 
     * why the sum appears in a peak class ?*/
    double sumIntens;

    public PeakInfo(double peakMz, double peakIntens, ArrayList<FragNode> candiFragNodeList) {
        this.peakMz = peakMz;
        this.peakIntens = peakIntens;
        this.candiFragNodeList = candiFragNodeList;
    }

    public PeakInfo(double peakMz, ArrayList<FragNode> candiFragNodeList) {
        this.peakMz = peakMz;
        this.candiFragNodeList = candiFragNodeList;
    }

    public void setSumIntens(double sumIntens) {
        this.sumIntens = sumIntens;
    }

    public double getPeakMz() {
        return this.peakMz;
    }

    public void setPeakMz(double peakMz) {
        this.peakMz = peakMz;
    }

    public void setPeakIntens(double peakIntens) {
        this.peakIntens = peakIntens;
    }

    public double getPeakIntens() {
        return this.peakIntens;
    }

    public ArrayList<FragNode> getCandiFragNodeList() {
        return this.candiFragNodeList;
    }

    public double getSumIntens() {
        return this.sumIntens;
    }

}
